depense:
    path:   /depense
    defaults: {_controller: depense_bundle_controller_depense_controller:indexAction }

ajout-depense:
    path:   /depense/ajout-depense
    defaults: {_controller: depense_bundle_controller_depense_controller:ajoutAction }

ajout-categorie:
    path:   /depense/ajout-categorie
    defaults: {_controller: depense_bundle_controller_depense_controller:ajoutCategorieAction }

suppression-depense:
    path: /depense/suppression-depense/{idDepense}
    defaults: {_controller: depense_bundle_controller_depense_controller:suppressionAction }

suppression-categorie:
    path: /depense/suppression-categorie/{idCategorie}
    defaults: {_controller: depense_bundle_controller_depense_controller:suppressionCategorieAction }

modification-depense:
    path: /depense/modification-depense/{idDepense}
    defaults: {_controller: depense_bundle_controller_depense_controller:modificationAction }

modification-pop-depense:
    path: /depense/modification-pop-depense/{idDepense}
    defaults: {_controller: depense_bundle_controller_depense_controller:modificationPopAction }

bilan:
    path:   /bilan
    defaults: {_controller: depense_bundle_controller_bilan_controller:indexAction  }

generation-bilan:
    path:   /generation-bilan
    defaults: {_controller: depense_bundle_controller_bilan_controller:generationBilanAction }