depense:
    path:   /depense
    defaults: {_controller: DepenseBundle:Depense:index }

ajout-depense:
    path:   /depense/ajout-depense
    defaults: {_controller: DepenseBundle:Depense:ajout }

ajout-categorie:
    path:   /depense/ajout-categorie
    defaults: {_controller: DepenseBundle:Depense:ajoutCategorie }

suppression-depense:
    path: /depense/suppression-depense/{idDepense}
    defaults: {_controller: DepenseBundle:Depense:suppression }

suppression-categorie:
    path: /depense/suppression-categorie/{idCategorie}
    defaults: {_controller: DepenseBundle:Depense:suppressionCategorie }

modification-depense:
    path: /depense/modification-depense/{idDepense}
    defaults: {_controller: DepenseBundle:Depense:modification }

modification-pop-depense:
    path: /depense/modification-pop-depense/{idDepense}
    defaults: {_controller: DepenseBundle:Depense:modificationPop }

bilan:
    path:   /bilan
    defaults: {_controller: depense_bundle_controller_bilan_controller:indexAction  }

generation-bilan:
    path:   /generation-bilan
    defaults: {_controller: depense_bundle_controller_bilan_controller:generationBilanAction }