imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    logos_directory: '%kernel.root_dir%/../web/uploads/logos'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "localhost"
        port:     "3306"
        dbname:   "Symfony"
        user:     "root"
        password: "root"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
    
    
fos_user:
    # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    db_driver:     orm                       
    # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    firewall_name: main                      
    # La classe de l'entité User que nous utilisons
    user_class:    UserBundle\Entity\User
     
    registration:
        confirmation:
            enabled:    true
            from_email:
                address:        siempre14@hotmail.fr
                sender_name:    Application AGC
      
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: email/registration.email.twig
            
  
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
            
    
           

    
    
    
# Swiftmailer Configuration
#swiftmailer:
#   transport: "smtp"
#   host:      "smtp.unicaen.fr"
#   username:  "lavieillef"
#   password:  "Blainville01"
#   spool:     { type: memory }
