commande:
    resource: "@CommandeBundle/Resources/config/routing.yml"

depense:
    resource: "@DepenseBundle/Resources/config/routing.yml"

bilan:
    resource: "@BilanBundle/Resources/config/routing.yml"

client:
    resource: "@ClientBundle/Resources/config/routing.yml"

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"

partenaire:
    resource: "@PartenaireBundle/Resources/config/routing.yml"

vitrine:
    resource: "@VitrineBundle/Resources/config/routing.yml"

user:
    resource: "@UserBundle/Resources/config/routing.yml"

application:
    resource: "@AppBundle/Resources/config/routing.yml"

