
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

index:
    path:   /index
    defaults: {_controller: IndexBundle:Index:index }
    
login:
    path:   /login
    defaults: {_controller: UserBundle:Security:login }
 
login_check:
    path:   /login_check
    
logout:
    path:   /logout
    #defaults: {_controller: UserBundle:Security:logout }
    
genus:
    path:   /genus/{genusName}
    defaults: {_controller: IndexBundle:Index:show }