# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username
                
    encoders:
        UserBundle\Entity\User: sha512

        
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            #anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            pattern:    ^/
            anonymous:  true
            http_basic: ~
            provider: main
            
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: application
            logout:
                path:   fos_user_security_logout
                target: accueil
                
            #remember_me:
                #key: %secret%
    
    role_hierarchy:
        ROLE_ADMIN :        ROLE_USER
        ROLE_SUPER_ADMIN:   [ ROLE_USER, ROLE_ADMIN ]
    
    access_control:
        - { path: ^/article, roles: ROLE_USER }
        - { path: ^/commande, roles: ROLE_USER }
        - { path: ^/client, roles: ROLE_USER }
        - { path: ^/bilan, roles: ROLE_ADMIN }
        - { path: ^/depense, roles: ROLE_ADMIN }
        - { path: ^/temoignages, roles: ROLE_ADMIN }
        - { path: ^/reservations, roles: ROLE_ADMIN }
        - { path: ^/utilisateur, roles: ROLE_SUPER_ADMIN }
