# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    commande_bundle_service_invoice_service: CommandeBundle\Service\InvoiceService
#    commande_bundle_controller_invoice_controller: CommandeBundle\Controller\FactureController
#
#services:
#    commande_bundle_service_invoice_service:
#        class: '%commande_bundle_service_invoice_service%'
#        arguments: ['@doctrine.orm.entity_manager']
#
#    commande_bundle_controller_invoice_controller:
#        class: '%commande_bundle_controller_invoice_controller%'
#        arguments: ['@commande_bundle_service_invoice_service']