# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    invoiceService.class : CommandeBundle\Service\InvoiceService
    invoiceController.class : CommandeBundle\Controller\FactureController

services:
    _defaults:
            autowire: true
            autoconfigure: true
            public: true
            synthetic: true


    CommandeBundle\:
            resouces: ../../src/CommandeBundle/*
            synthetic: true

    invoiceService:
        class: CommandeBundle\Service\InvoiceService
    invoiceController:
        class: CommandeBundle\Controller\FactureController
        arguments: ['@invoiceService']