parameters:
    commande_bundle_service_invoice_service: CommandeBundle\Service\InvoiceService
    commande_bundle_service_commande_service: CommandeBundle\Service\CommandeService
    commande_bundle_service_booking_service: CommandeBundle\Service\BookingService
    commande_bundle_controller_invoice_controller: CommandeBundle\Controller\FactureController
    commande_bundle_controller_commande_controller: CommandeBundle\Controller\CommandeController
