commande:
    path:   /commande
    defaults: {_controller: commande_bundle_controller_commande_controller:indexAction }

view-order:
    path:   /commande/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:viewAction }

ajout-commande:
    path:   /commande/ajout-commande
    defaults: {_controller: commande_bundle_controller_commande_controller:ajoutAction }

ajout-article-commande-pop:
    path:   /commande/ajout-article-commande-pop/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:ajoutArticlePopAction }

ajout-article-commande:
    path:   /commande/ajout-article-commande/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:ajoutArticleAction }



ajout-lot-commande-pop:
    path:   /commande/ajout-lot-commande-pop/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:ajoutLotPopAction }

ajout-lot-commande:
    path:   /commande/ajout-lot-commande/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:ajoutLotAction }

suppression-lot-commande:
    path:   /commande/suppression-lot-commande/{idLot}/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:suppressionLotAction }





suppression-article-commande:
    path:   /commande/suppression-article-commande/{idArticle}/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:suppressionArticleAction }

suppression-commande:
    path:   /commande/suppression-commande/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:suppressionAction }

commande-paye:
    path:   /commande/commande-paye/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:payeAction }

générer-ultime-facture:
    path:   /commande/générer-ultime-facture/{idCommande}
    defaults: {_controller: commande_bundle_controller_invoice_controller:ultimeFactureAction }

générer-facture:
    path:   /commande/générer-facture/{idCommande}
    defaults: {_controller: commande_bundle_controller_invoice_controller:factureAction }

générer-devis:
    path:   /commande/générer-devis/{idCommande}
    defaults: {_controller: commande_bundle_controller_invoice_controller:devisAction }

archiver-commande:
    path:   /commande/archiver-commande/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:archiverAction }

voir-commandes-archivees:
    path:   /commande/commandes-archivees
    defaults: {_controller: commande_bundle_controller_commande_controller:commandesArchiveesAction }

retour-location:
    path:   /commande/retour-location/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:retourLocationAction }

depart-location:
    path:   /commande/depart-location/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:departLocationAction }

versement-acompte-pop:
    path:   /commande/versement-acompte-pop/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:versementAcomptePopAction }

versement-acompte:
    path:   /commande/versement-acompte/{idCommande}
    defaults: {_controller: commande_bundle_controller_commande_controller:versementAcompteAction }